language: ruby
sudo: false

rvm:
- "2.0"
- "2.1"
- "2.2"

env:
  global:
    KAFKA_REST_URL: "http://localhost:8082"

before_script:
- make confluent/start
- make test/create_kafka_topics

after_script:
- make confluent/stop

before_cache:
- rm -rf confluent/logs

cache:
  directories:
  - confluent
